steps:
  # This step runs the unit tests on the app
  - name: 'openjdk:16-alpine3.13'
    id: Test
    entrypoint: /bin/sh
    args:
      - -c
      - './mvnw test'

  - name: 'openjdk:16-alpine3.13'
    id: Package
    entrypoint: /bin/sh
    args:
      - -c
      - './mvnw package'

  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-world:$SHORT_SHA'
      - '.'

  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hello-world:$SHORT_SHA'

artifacts:
  objects:
    location: 'gs://packagetinyurl323522/'
    paths: ['target/tinyurl-0.0.1-SNAPSHOT.jar']
